### PR TITLE
Feature/add token and request permission interceptors

### PR DESCRIPTION
**Pull request by clewis1**
Configure token and request permission interceptors
https://companieshouse.atlassian.net/browse/IDVA3-537

### CODE REVIEW

**Comment by clewis1** [comment]
Pending https://github.com/companieshouse/authentication-service/pull/591 approval.

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by clewis1** [comment]
https://github.com/companieshouse/authentication-service/pull/591 Approved. 
Now ready for PR.

**Review by AlisonGriffiths — CHANGES_REQUESTED** [review]
In the code, can you update the BaseControllerIT.setupEricTokenPermissions() to now reflect the correct permissions.

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by AlisonGriffiths — APPROVED** [review]

**Pull request merged**
